# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
executors:
  node-and-browsers:
    docker:
      - image: cypress/browsers:node14.16.0-chrome89-ff86
    environment:
      - CHROME_BIN: /usr/bin/google-chrome
workflows:
  build:
    jobs:
      - cypress/install:
          name: install_cypress
          yarn: true
          executor: node-and-browsers
      - cypress/run:
          name: 'E2E - No Config'
          browser: chrome
          executor: node-and-browsers
          yarn: true
          start: yarn start:demo:no-config
          wait-on: 'http://localhost:4200'
          requires:
            - install_cypress
      - cypress/run:
          name: 'E2E - With Config'
          browser: chrome
          executor: node-and-browsers
          yarn: true
          start: yarn start:demo:config
          wait-on: 'http://localhost:4200'
          requires:
            - install_cypress
